import os 
os.mkdir('testdir')
file = open('testdir/testfile.txt', 'w')
file.write('Stats for x:\n')
file.write('easy + games (num_games, total_time, num_questions, correct_questions):\n')
file.write('0 0 0 0\n')
file.write('easy - games (num_games, total_time, num_questions, correct_questions):\n')
file.write('0 0 0 0\n')
file.write('easy * games (num_games, total_time, num_questions, correct_questions):\n')
file.write('0 0 0 0\n')
file.write('medium + games (num_games, total_time, nuquestions, correct_questions):\n')
file.write('0 0 0 0\n')
file.write('medium - games (num_games, total_time, nuquestions, correct_questions):\n')
file.write('0 0 0 0\n')
file.write('medium * games (num_games, total_time, nuquestions, correct_questions):\n')
file.write('0 0 0 0\n')
file.write('hard + games (num_games, total_time, num_questions, correct_questions):\n')
file.write('0 0 0 0\n')
file.write('hard - games (num_games, total_time, num_questions, correct_questions):\n')
file.write('0 0 0 0\n')
file.write('hard * games (num_games, total_time, num_questions, correct_questions):\n')
file.write('0 0 0 0\n')
